apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging
  prune: true
  wait: true
  timeout: 5m0s
  patches:
    - patch: |
        - op: add
          path: /spec/values/ingress/hosts/-
          value:
            host: podinfo.staging
            paths:
              - path: "/"
                pathType: Prefix
      target:
        kind: Helmrelease
        name: podinfo