apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: mysql
      version: '9.10.9'
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: default
      interval: 1m
  values:
    auth:
      database: "mydatabase"
      username: "myuser"
      password: "mypassword"